/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors.$vendorId'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/vendors/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/vendors/$vendorId'
    | '/dashboard/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/vendors/$vendorId'
    | '/dashboard'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/vendors/$vendorId'
    | '/dashboard/'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
